# Generated by Django 3.1.8 on 2024-08-26 14:32

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, validators=[myapp.models.checkDns])),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
