# Generated by Django 3.1.8 on 2024-08-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
    ]
