version: '3'

services:
  db:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_feedback_py:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: site
      POSTGRES_PASSWORD: app2024
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-content:/usr/share/nginx/html:ro
    ports:
      - "6680:80"
  app:
    build: .
    restart: always
    container_name: pweb-py
    volumes:
      - ./web:/app
    working_dir: /app
volumes:
  base_feedback_py:
    external: true