version: "3.9"

services:
  db:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_feedback:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: site
      POSTGRES_PASSWORD: app2024
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5475:5432"
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-content:/var/www/html:ro
    ports:
      - "6980:80"
  app:
    depends_on:
      - nginx
      - db
    build:
      context: ./low-level-php
    restart: always
    container_name: pweb-php
    volumes:
      - ./app:/app
    command: bash -c "composer install && php-fpm"
    #Nao publique porta
volumes:
  base_feedback:
    external: true